data:
  AzureWebJobsStorage: ''
  FUNCTIONS_WORKER_RUNTIME: ZG90bmV0
apiVersion: v1
kind: Secret
metadata:
  name: simple
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-functions-secrets
type: Opaque
stringData:
  host.json: |-
    {
      "masterKey": {
        "name": "master",
        "value": "{REPLACEME}",
        "encrypted": false
      },
      "functionKeys": [ ]
    }
  httpTrigger.json: |-
    {
      "keys": [
        {
          "name": "default",
          "value": "{REPLACEME}",
          "encrypted": false
        }
      ]
    }
---
apiVersion: v1
kind: Service
metadata:
  name: simple-http
  namespace: default
  annotations:
    osiris.deislabs.io/enabled: true
    osiris.deislabs.io/deployment: simple-http
spec:
  selector:
    app: simple-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-http
  namespace: default
  labels:
    app: simple-http
  annotations:
    osiris.deislabs.io/enabled: true
    osiris.deislabs.io/minReplicas: 1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-http
  template:
    metadata:
      labels:
        app: simple-http
    spec:
      containers:
      - name: simple-http
        image: bjd145.azurecr.io/simple:1.0
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: keda
        envFrom:
        - secretRef:
            name: simple
        env:
        - name: AzureWebJobsSecretStorageType
          value: files
        volumeMounts:
        - name: secrets
          mountPath: "/azure-functions-host/Secrets"
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: azure-functions-secrets
---

